### bcntb.plotly.estimate.R ###
### DESCRIPTION ########################################################
# This script dinamically creates estimate 3D scatterplot from report file
# generated by the bcntb.estimate.R script

### HISTORY ###########################################################
# Version		Date					Coder						Comments
# 1.0			2017/06/07			Stefano					starting from the scratch

### PARAMETERS #######################################################
current_dir <- getwd()
suppressMessages(library(optparse))
suppressMessages(library(plotly))

##### COMMAND LINE PARAMETERS ###############################################
### Here we take advantage of Optparse to manage arguments####
### Creating list of arguments ###
option_list = list(
  make_option(c("-r", "--report"), action="store", default=NA, type='character',
              help="File containing estimate report (bcntb.estimate.R)"),
  make_option(c("-d", "--dir"), action="store", default=NA, type='character',
              help="Default directory for output")
)

opt = parse_args(OptionParser(option_list=option_list))

# reading mclust report file
estimate.report <- read.table(opt$report, sep = "\t", header = TRUE, stringsAsFactors = FALSE)

#### initialising colorbar style
cb_style<-list(
  colorbar = list(title = "Tumour Purity",
                  titleside = "top",
                  titlefont = list(
                    family = "Helvetica Neue",
                    size = 15
                  ),
                  tickfont = list (
                    family = "Helvetica Neue",
                    size = 12,
                    color = 'grey'
                  ),
                  ypad = 10,
                  y = 3,
                  thickness = 15,
                  nticks = 10,
                  xanchor = 'center',
                  xpad = 10),
  size = 5, symbol = 'circle', cmin=0, cmax=1, cauto = T)

### initialising plot margins
margins <- list(
  l = 10,
  r = 10,
  b = 10,
  t = 10,
  pad = 1
)

### create plotly scatterplot
p <- plot_ly(estimate.report,
        x =~ StromalScore,
        y =~ ImmuneScore,
        z =~ ESTIMATEScore,
        color =~ TumorPurity,
        hoverinfo = 'text',
        text = paste('Sample Name:', estimate.report$File_name,
                     '<br><br>StromalScore:', estimate.report$StromalScore,
                     '<br>ImmuneScore:', estimate.report$ImmuneScore,
                     '<br>ESTIMATEScore:', estimate.report$ESTIMATEScore,
                     '<br><br><b>Tumour Purity</b>:', estimate.report$TumorPurity),
        marker = cb_style,
        width = '800px'
) %>%
  add_markers() %>%
  layout(scene = list(xaxis = list(title = 'StromalScore', orientation = "v"),
                      yaxis = list(title = 'ImmuneScore'),
                      zaxis = list(title = 'EstimateScore')),
         margin = margins,
         title = ""
  )

## defining plot file name
estimate_filename = paste(opt$dir,"estimate.html",sep = "/")

## saving generated plot into web page
htmlwidgets::saveWidget(p, estimate_filename, selfcontained = FALSE)
